/**
 * app/api/bug-reports/route.js
 * GET  — list general bug reports (project_id IS NULL)
 * POST — any authenticated employee can submit a bug report (with optional attachments)
 */
import { NextResponse } from "next/server";
import { getSession }   from "../../../lib/auth";
import { query }        from "../../../lib/db";

export async function GET() {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const isAdmin = session.role === "ADMIN";
  const isDev   = session.sub_role_dept === "Development";
  const seeAll  = isAdmin || isDev;

  try {
    let rows;
    if (seeAll) {
      /* Admins and developers see ALL general + assigned bug reports */
      ({ rows } = await query(`
        SELECT pb.*, u.name AS reporter_name,
               p.name AS project_name
        FROM project_bugs pb
        JOIN users u ON u.id = pb.reported_by
        LEFT JOIN projects p ON p.id = pb.project_id
        ORDER BY
          CASE pb.status WHEN 'open' THEN 1 WHEN 'in_progress' THEN 2 ELSE 3 END,
          CASE pb.priority WHEN 'Urgent' THEN 1 WHEN 'High' THEN 2 WHEN 'Normal' THEN 3 ELSE 4 END,
          pb.created_at DESC
      `));
    } else {
      /* Others see only their own (all statuses, incl. resolved for reference) */
      ({ rows } = await query(`
        SELECT pb.*, u.name AS reporter_name,
               p.name AS project_name
        FROM project_bugs pb
        JOIN users u ON u.id = pb.reported_by
        LEFT JOIN projects p ON p.id = pb.project_id
        WHERE pb.reported_by = $1
        ORDER BY pb.created_at DESC
      `, [session.id]));
    }
    return NextResponse.json({ success: true, bugs: rows });
  } catch (err) {
    console.error("[BUG-REPORTS:GET]", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function POST(req) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const {
      title,
      description,
      priority        = "Normal",
      project_id      = null,   // optional — assign to a project immediately
      attachment_urls = [],     // optional uploaded file URLs
    } = await req.json();

    if (!title?.trim()) return NextResponse.json({ error: "Title is required" }, { status: 400 });

    /* id auto-generated by DB DEFAULT gen_random_uuid()::text */
    const { rows: [bug] } = await query(`
      INSERT INTO project_bugs
        (project_id, title, description, priority, status, reported_by, attachment_urls)
      VALUES ($1, $2, $3, $4, 'open', $5, $6)
      RETURNING *
    `, [project_id, title.trim(), description || null, priority, session.id, attachment_urls]);

    return NextResponse.json({ success: true, bug });
  } catch (err) {
    console.error("[BUG-REPORTS:POST]", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
